export const data = {
  bg: [
    { img: "/traits/bg/bg (1).png", name: "Fallingmen" },
    { img: "/traits/bg/bg (2).png", name: "Hellspin" },
    { img: "/traits/bg/bg (3).png", name: "Lips" },
    { img: "/traits/bg/bg (4).png", name: "Paint Spill" },
    { img: "/traits/bg/bg (5).png", name: "Pink Worms" },
    { img: "/traits/bg/bg (6).png", name: "Smileys" },
    { img: "/traits/bg/bg (7).png", name: "Special Mushrooms" },
    { img: "/traits/bg/bg (8).png", name: "Special Trippey Egg" },
    { img: "/traits/bg/bg (9).png", name: "TMC Logo" },
    { img: "/traits/bg/bg (10).png", name: "Trippey Blue" },
  ],
  clothing: [
    { img: "/traits/clothing/cloth (1).png", name: "Basketball Jersey" },
    { img: "/traits/clothing/cloth (2).png", name: "Care Bearsuit" },
    { img: "/traits/clothing/cloth (3).png", name: "Clucky Eabro Shirt" },
    { img: "/traits/clothing/cloth (4).png", name: "Dead Cluck Shirt" },
    { img: "/traits/clothing/cloth (5).png", name: "Hots Auce Shirt" },
    { img: "/traits/clothing/cloth (6).png", name: "Biker Jacket" },
    { img: "/traits/clothing/cloth (7).png", name: "S&M" },
    { img: "/traits/clothing/cloth (8).png", name: "Smile" },
    { img: "/traits/clothing/cloth (9).png", name: "Wife Beater" },
    { img: "/traits/clothing/cloth (10).png", name: "Wrestling Tank" },
  ],
  chicken: [
    { img: "/traits/chicken/chicken (1).png", name: "American" },
    { img: "/traits/chicken/chicken (2).png", name: "Black Alien" },
    { img: "/traits/chicken/chicken (3).png", name: "Bones" },
    { img: "/traits/chicken/chicken (4).png", name: "Cyborg" },
    { img: "/traits/chicken/chicken (5).png", name: "Diablo" },
    { img: "/traits/chicken/chicken (6).png", name: "Holy Third Eye" },
    { img: "/traits/chicken/chicken (7).png", name: "Molly Head" },
    { img: "/traits/chicken/chicken (8).png", name: "Original" },
    { img: "/traits/chicken/chicken (9).png", name: "Radio Active" },
    { img: "/traits/chicken/chicken (10).png", name: "Worm Worshipper" },
  ],
  shadow: [{ img: "/traits/shadow/shadow.png", name: "Shadow Permanent" }],
  face: [
    { img: "/traits/face/face (1).png", name: "Cluckerz" },
    { img: "/traits/face/face (2).png", name: "Drippy Skeleton" },
    { img: "/traits/face/face (3).png", name: "Drunk Uncle" },
    { img: "/traits/face/face (4).png", name: "Gangster" },
    { img: "/traits/face/face (5).png", name: "Ghosty" },
    { img: "/traits/face/face (6).png", name: "Happy Trippy" },
    { img: "/traits/face/face (7).png", name: "Jason Mask" },
    { img: "/traits/face/face (8).png", name: "Screaming Shades" },
    { img: "/traits/face/face (9).png", name: "Shroom Head" },
    { img: "/traits/face/face (10).png", name: "Skull Mask" },
    { img: "/traits/face/face (11).png", name: "Spirited Away" },
    { img: "/traits/face/face (12).png", name: "Super High" },
  ],
  hair: [
    { img: "/traits/hair/hair (1).png", name: "Blue Prom" },
    { img: "/traits/hair/hair (2).png", name: "Cluckerz Beanie" },
    { img: "/traits/hair/hair (3).png", name: "Corn Rows" },
    { img: "/traits/hair/hair (4).png", name: "Egg" },
    { img: "/traits/hair/hair (5).png", name: "Flames" },
    { img: "/traits/hair/hair (6).png", name: "Greaser" },
    { img: "/traits/hair/hair (7).png", name: "Horns" },
    { img: "/traits/hair/hair (8).png", name: "Shaved" },
    { img: "/traits/hair/hair (9).png", name: "Spikes" },
    { img: "/traits/hair/hair (10).png", name: "Trippy Egg" },
  ],
  color: [
    { img: "/traits/face-color/color (1).png", name: "Blue Flames" },
    { img: "/traits/face-color/color (2).png", name: "Gold" },
    { img: "/traits/face-color/color (3).png", name: "Green" },
    { img: "/traits/face-color/color (4).png", name: "Orange" },
    { img: "/traits/face-color/color (5).png", name: "Pink" },
    { img: "/traits/face-color/color (6).png", name: "Red" },
    { img: "/traits/face-color/color (7).png", name: "Teal" },
  ],
};

export default data;
